### ISSUE TITLE
Building Library Mod Type using pyproject.toml

### ISSUE THREAD

**Issue by Ry0511** [bl-sdk/mods_base#12]
When loading parameters via a `pyproject.toml` in `build_mod( ... )` you can specify the `mod_type` to `Library` however this does not make the mod a library as you also need to pass `cls=Library` into the function. Currently there is no warning/error for forgetting to do this.

#### Snippet

```toml
[project]
name = "My Library"
version = "1.0"
authors = [{ name = "-Ry" }]
description = "Useful stuff here"

[tool.sdkmod]
mod_type = "Library"
supported_games = "BL1"
coop_support = "Unknown"
```

```py
from mods_base import build_mod
build_mod()  # Without cls=Library this should raise an error or a warning message (or the documentation should mention this)
```

This tripped me up a little while ago thought I would raise an issue since the documentation doesn't seem to say anything about it.

#### Relevant Links
https://github.com/bl-sdk/mods_base/blob/master/mod_factory.py#L23
